### PR TITLE
Get a release in shape

### PR DESCRIPTION
**Pull request by sjakobi**
@lpsmith: I have asked @jaspervdj to make a release as there has been so little indication that you would do it reasonably soon.

I hope that you can understand this as there are so many people waiting! :)

### CODE REVIEW

**Comment by DanBurton** [comment]
I have built & tested this against lts-11 (ghc 8.2) and nightly-2018-03-14 (ghc 8.4). It builds and the tests pass on both.

**Comment by sjakobi** [comment]
I pulled back a commit to make the Semigroup instance unconditional because I got a funky build error with GHC-7.0. Let me fix that first.

**Comment by jaspervdj** [comment]
Thanks a lot for the work @sjakobi! After some discussion I think an unconditional instance with an
```
if !impl(ghc >= 8.0)
  build-depends: semigroups == 0.18.*
```
So we don't introduce the dependency overhead on recent GHCs.  Ping me when you want to discuss or if you want me to upload the release.

**Comment by sjakobi** [comment]
03ff5b0 works for GHC-7.0.4 upwards.

> build-depends: semigroups == 0.18.*

Is there a reason for the constraint or is that simply a preference?

**Comment by hvr** [comment]
> Is there a reason for the constraint or is that simply a preference?

mostly preference; if you can prove that it can be relaxed downwards, feel free to relax.

**Comment by sjakobi** [comment]
This way it still works with LTS-2 :)

**Comment by jaspervdj** [comment]
Thanks again for all the work @sjakobi and @DanBurton!  I have merged this to my fork and uploaded a release.

This PR should be closed.  I will open a new PR to get the changes in my fork back upstream.

**Comment by sjakobi** [comment]
Thanks for stepping up, @jaspervdj!

**Pull request closed without merging**
