### PR TITLE
Compatibility with Semigroup/Monoid proposal

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by bgamari** [comment]
Ping?

**Comment by asr** [comment]
GHC 8.4.1-alpha1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2017-December/015235.html). While testing Agda with this version of GHC I got the following error:

```
$ cabal install
Blaze/ByteString/Builder/Internal/Write.hs:130:14: error:
    The INLINE pragma for ‘sconcat’ lacks an accompanying binding
    |
130 |   {-# INLINE sconcat #-}
    |              ^^^^^^^

Blaze/ByteString/Builder/Internal/Write.hs:131:3: error:
    ‘sconcat’ is not a (visible) method of class ‘Semigroup’
    |
131 |   sconcat = foldr (<>) mempty
    |   ^^^^^^^

Blaze/ByteString/Builder/Internal/Write.hs:152:14: error:
    The INLINE pragma for ‘sconcat’ lacks an accompanying binding
    |
152 |   {-# INLINE sconcat #-}
    |              ^^^^^^^

Blaze/ByteString/Builder/Internal/Write.hs:153:3: error:
    ‘sconcat’ is not a (visible) method of class ‘Semigroup’
    |
153 |   sconcat = foldr (<>) mempty
    |   ^^^^^^^
```

Since *this* PR fix the problem, could you merge it, please?

**Comment by asr** [comment]
GHC 8.4.1-alpha3 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2018-February/015354.html). Please, could someone merge this PR?

**Comment by asr** [comment]
GHC 8.4.1 was released. Any news?

**Pull request merged**
